name: Sync data dictionary

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # start of every day

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    container: curlimages/curl:latest
    steps:
      - run: |
          curl -X POST -H "X-Auth-Key: ${{ secrets.SYNC_AUTH_KEY }}" -s -S -f https://data-dictionary.staging-service.newrelic.com/sync

  sync-prod:
    runs-on: ubuntu-latest
    container: curlimages/curl:latest
    needs: sync-staging
    steps:
      - run: |
          curl -X POST -H "X-Auth-Key: ${{ secrets.SYNC_AUTH_KEY }}" -s -S -f https://data-dictionary.service.newrelic.com/sync

  sync-eu:
    runs-on: ubuntu-latest
    container: curlimages/curl:latest
    needs: sync-staging
    steps:
      - run: |
          curl -X POST -H "X-Auth-Key: ${{ secrets.SYNC_AUTH_KEY }}" -s -S -f https://data-dictionary.service.eu.newrelic.com/sync
